name: Database Migrations

on:
  push:
    branches:
      - main # for production
      - staging # for staging environment
    paths:
      - 'packages/database/**' # Only trigger when database files change

jobs:
  migrate:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    
    # Define different environments based on branch
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.4
          run_install: false
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run database migrations
        run: pnpm db:push
        env:
          # Database connection settings from GitHub secrets
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          
      - name: Notify on success
        if: success()
        run: echo "Database migrations completed successfully!" 
